CREATE TABLE AS_COMERCIO
(
  ID_COMERCIO   NUMBER(10)                 NOT NULL,
  NOM_COMERCIO  VARCHAR2(50)               NOT NULL,
  AFORO_MAXIMO  NUMBER(5)                  NOT NULL
)
/


ALTER TABLE AS_COMERCIO ADD (
  CONSTRAINT AS_COMERCIO_PK
  PRIMARY KEY
  (ID_COMERCIO)
)
/


CREATE TABLE AS_SERVICIO
(
  ID_SERVICIO    NUMBER(10)                NOT NULL,
  ID_COMERCIO    NUMBER(10)                NOT NULL,
  NOM_SERVICIO   VARCHAR2(50)              NOT NULL,
  HORA_APERTURA  DATE                      NOT NULL,
  HORA_CIERRE    DATE                      NOT NULL,
  DURACION       NUMBER(5)
)
/


ALTER TABLE AS_SERVICIO ADD (
  CONSTRAINT AS_SERVICIO_PK
  PRIMARY KEY
  (ID_SERVICIO)
)
/


CREATE TABLE AS_TURNO
(
  ID_TURNO     NUMBER(10)                  NOT NULL,
  ID_SERVICIO  NUMBER(10)                  NOT NULL,
  FECHA_TURNO  DATE                        NOT NULL,
  HORA_INICIO  DATE                        NOT NULL,
  HORA_FIN     DATE                        NOT NULL,
  ESTADO       VARCHAR2(1)                 NOT NULL
)
/


ALTER TABLE AS_TURNO ADD (
  CONSTRAINT AS_TURNO_PK
  PRIMARY KEY
  (ID_TURNO)
)
/


CREATE TABLE AS_USUARIO
(
  ID_USUARIO  NUMBER(10)                   NOT NULL,
  USERNAME    VARCHAR2(10)                 NOT NULL,
  PSSWRD      VARCHAR2(255)                NOT NULL
)
/


ALTER TABLE AS_USUARIO ADD (
  CONSTRAINT AS_USUARIO_PK
  PRIMARY KEY
  (ID_USUARIO)
)
/


ALTER TABLE AS_SERVICIO ADD (
  CONSTRAINT AS_SERVICIO_FK 
  FOREIGN KEY (ID_COMERCIO) 
  REFERENCES AS_COMERCIO (ID_COMERCIO)
)
/

ALTER TABLE AS_TURNO ADD (
  CONSTRAINT AS_TURNO_FK 
  FOREIGN KEY (ID_SERVICIO) 
  REFERENCES AS_SERVICIO (ID_SERVICIO)
)
/

CREATE UNIQUE INDEX UQ_AS_TURNO1 
  ON AS_TURNO(ID_SERVICIO, TRUNC(FECHA_TURNO),HORA_INICIO)
/

--TEST DATA
SET DEFINE OFF;
Insert into AS_COMERCIO
   (ID_COMERCIO, NOM_COMERCIO, AFORO_MAXIMO)
 Values
   (1, 'COM1', 200);
Insert into AS_COMERCIO
   (ID_COMERCIO, NOM_COMERCIO, AFORO_MAXIMO)
 Values
   (2, 'COM2', 250);
COMMIT;


SET DEFINE OFF;
Insert into AS_SERVICIO
   (ID_SERVICIO, ID_COMERCIO, NOM_SERVICIO, HORA_APERTURA, HORA_CIERRE, 
    DURACION)
 Values
   (1, 2, 'SER1', TO_DATE('1/01/1900 10:00:00 AM', 'DD/MM/YYYY HH:MI:SS AM'), TO_DATE('1/01/1900 2:00:00 PM', 'DD/MM/YYYY HH:MI:SS AM'), 
    30);
Insert into AS_SERVICIO
   (ID_SERVICIO, ID_COMERCIO, NOM_SERVICIO, HORA_APERTURA, HORA_CIERRE, 
    DURACION)
 Values
   (2, 2, 'SER2', TO_DATE('1/01/1900 10:00:00 AM', 'DD/MM/YYYY HH:MI:SS AM'), TO_DATE('1/01/1900 2:00:00 PM', 'DD/MM/YYYY HH:MI:SS AM'), 
    60);
COMMIT;

--passwords are already encrypted
SET DEFINE OFF;
Insert into AS_USUARIO
   (ID_USUARIO, USERNAME, PSSWRD) /* test123 */ 
 Values
   (1, 'DARE', 'dGVzdDEyMw==');
Insert into AS_USUARIO
   (ID_USUARIO, USERNAME, PSSWRD) /* hiring */ 
 Values
   (2, 'ASESOFTWA', 'aGlyaW5n');
COMMIT;
